config/routes.rb
Rails.application.routes.draw do
  root 'spenders#home'

  resources :spenders do
  	resources :expenditures
  end

  # resources :spenders , only: [] do
  # 	resources :expenditures
  # end

end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  belongs_to :spender
end

app/models/spender.rb
class Spender < ActiveRecord::Base
	has_many :expenditures , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
		
	def index
		@spender = Spender.find(params[:spender_id])
		@expenditures = Expenditure.where(:spender_id => params[:spender_id])
	end

	def show
		@spender = Spender.find(params[:spender_id])
		@expenditure = @spender.expenditures.find(params[:id])
	end

	def new
		@spender = Spender.find(params[:spender_id])
		@expenditure = @spender.expenditures.new #plural beacause a spender has many expendnitures.
	end

	def edit
		@spender = Spender.find(params[:spender_id])
		@expenditure = @spender.expenditures.find(params[:id])
	end

	def create
		@spender = Spender.find(params[:spender_id])
		@expenditure = @spender.expenditures.create(expenditure_params)
		# redirect_to spender_path(@spender)
		render "show"
	end


	def update
		@spender = Spender.find(params[:spender_id])
		@expenditure = @spender.expenditures.find(params[:id])

		if @expenditure.update(expenditure_params)
			render "show"
		else
			render 'edit'
		end
	end

	def destroy
		@spender = Spender.find(params[:spender_id])
		@expenditure = @spender.expenditures.find(params[:id])
		@expenditure.destroy
		redirect_to spender_expenditures_path(@spender)
	end

	private
		def expenditure_params
			params.require(:expenditure).permit(:item, :price , :category )
		end
end

app/controllers/spenders_controller.rb
class SpendersController < ApplicationController
	def home
	end
	
	def index
		@spenders = Spender.all
	end

	def show
		@spender = Spender.find(params[:id])
		@count = @spender.expenditures.count

		if @count == 0 
			@total = @average = 0
		else 
			expenditures = @spender.expenditures
			prices = []
			expenditures.each do |expenditure|
				prices << expenditure.price
			end

			@total = prices.inject(:+)
			@average =  @total / @count
		end
	end

	def new
		@spender = Spender.new
	end

	def edit
		@spender = Spender.find(params[:id])
	end

	def create
		@spender = Spender.new(spender_params)		

		if @spender.save
			redirect_to @spender
		else
			render "new"
		end
	end

	def update
		@spender = Spender.find(params[:id])

		if @spender.update(spender_params)
			redirect_to @spender
		else
			render 'edit'
		end
	end

	def destroy
		@spender = Spender.find(params[:id])
		@spender.destroy

		redirect_to spenders_path
	end

	private
		def spender_params
			params.require(:spender).permit(:name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenditures/_expenditure.html.erb
<p>
  <strong>Purchase:</strong>
  <%= expenditure.item %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= expenditure.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= expenditure.category %>
</p>

<p>
  <%= link_to 'Destroy expenditure', [expenditure.spender, expenditure],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/expenditures/_form.html.erb
<%= form_for([@spender, @expenditure]) do |f| %>  <!-- ... url  -->

  <% if @expenditure.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@expenditure.errors.count, "error") %> prohibited this expenditure from being saved:
      </h2>

      <ul>
        <% @expenditure.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :purchase %><br>
    <%= f.text_field :item , :size => 30 %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price , :size => 30 %>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category , :size => 30 %>

   <!--    <select>
          <option value="" disabled="disabled" selected="selected"></option>
          <option value="1">Food</option>
          <option value="2">Transport</option>
          <option value="3">Excursion</option>
          <option value="4">Laundry</option>
          <option value="4">Sundries</option>
      </select> -->
      
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Edit expenditure</h1>

<%= render 'form' %> 

<%= link_to 'Back', spender_expenditure_path(@spender, @expenditure)%>

app/views/expenditures/index.html.erb
<h1>Expenditures</h1>

<table class = "table">
<tbody>
	<% @expenditures.each do |expenditure| %>
	<tr>
		<td><%= expenditure.item %></td> 
		<td><%= link_to 'Show', spender_expenditure_path(@spender, expenditure) %></td>
	</tr>
	<% end %>
</tbody>
</table>

</br>

<%= link_to 'New Expenditure', new_spender_expenditure_path(@spender) %> | <%= link_to 'Back', spender_path(@spender) %>

app/views/expenditures/new.html.erb
<h1>New expenditure</h1>

<%= form_for [@spender, @expenditure] do |f| %>

  <% if @expenditure.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@expenditure.errors.count, "error") %> prohibited this expenditure from being saved:
      </h2>

      <ul>
        <% @expenditure.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :purchase%><br>
    <%= f.text_field :item , :size => 30 %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price , :size => 30 %>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category , :size => 30 %>

<!--       <select>
          <option value="" disabled="disabled" selected="selected"></option>
          <option value="1">Food</option>
          <option value="2">Transport</option>
          <option value="3">Excursion</option>
          <option value="4">Laundry</option>
          <option value="4">Sundries</option>
      </select> -->
      
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>



<%= link_to "Back", spender_expenditures_path(params[:spender_id]) %>

app/views/expenditures/show.html.erb
<h1>Expenditure:</h1>

<p>
  <strong>Purchase:</strong>
  <%= @expenditure.item %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @expenditure.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expenditure.category %>
</p>

<%= link_to 'Edit', edit_spender_expenditure_path(@spender, @expenditure) %> |

<%= link_to 'Delete expenditure', [@expenditure.spender, @expenditure],method: :delete, data: { confirm: 'Are you sure?' } %> |

<%= link_to 'Back', spender_expenditures_path(@spender) %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spenders/_form.html.erb
<%= form_for @spender do |f| %>

  <% if @spender.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@spender.errors.count, "error") %> prohibited this spender from being saved:
      </h2>

      <ul>
        <% @spender.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.label :name %>
	<div><%= f.text_field :name , :size => 30 %></div> </br>
	<%= f.submit %>	
<% end %>

app/views/spenders/edit.html.erb
<h1>Edit Spender</h1>

<%= render 'form' %> 

<%= link_to 'Back', spender_path %>

app/views/spenders/home.html.erb
<h1>BruBudget</h1>

<%= link_to 'Spenders', spenders_path %>

app/views/spenders/index.html.erb
<h1>Spenders</h1>

<table class = "table">
<tbody>
	<% @spenders.each do |spender| %>
	<tr>
		<td><%= spender.name %> </td>
		<td class= "link"><%= link_to 'Show', spender_path(spender) %></td>
	</tr>
	<% end %>
</tbody>
</table>

</br>

<%= link_to 'New spender', new_spender_path %> 

app/views/spenders/new.html.erb
<h1>New spender</h1>

<%= render 'form' %> </br>

<%= link_to "Back", spenders_path %>

app/views/spenders/show.html.erb
<h1><%= @spender.name %></h1>

<h3>Summary </h3>


<table class = "table">
<tbody>
	<tr>
		<td>Number of transactions</td>
		<td><%= @count %></td>
	</tr>
	<tr>
		<td>Total amount spent</td>
		<td>R<%= @total %></td>
	</tr>
	<tr>
		<td>Average amount spent per transaction</td>	
		<td>R<%= @average %></td>		
	</tr>
</tbody>
</table>

<br>

<%= link_to 'Edit', edit_spender_path(@spender) %> |

<%= link_to 'Delete', spender_path(@spender),
         method: :delete,
         data: { confirm: 'Are you sure?' } %> |

<%= link_to 'Back', spenders_path %> 

<br>


<%= link_to 'Expenditures',spender_expenditures_path(@spender) %>